/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author CARLOS
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        btnAlumnos = new javax.swing.JButton();
        btnCursos = new javax.swing.JButton();
        btnProfesores = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menualumnos = new javax.swing.JMenu();
        menucursos = new javax.swing.JMenu();
        menuprofesores = new javax.swing.JMenu();
        menunotas = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAlumnos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FELIZ.GIF"))); // NOI18N
        btnAlumnos.setText("Alumnos");
        btnAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });

        btnCursos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar.jpg"))); // NOI18N
        btnCursos.setText("Cursos");
        btnCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosActionPerformed(evt);
            }
        });

        btnProfesores.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b_usrcheck.png"))); // NOI18N
        btnProfesores.setText("Profesores");
        btnProfesores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesoresActionPerformed(evt);
            }
        });

        btnNotas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        btnNotas.setText("Notas");
        btnNotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PANEL DE CONTROL");

        jMenuBar1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jMenu4.setText("Inicio");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Mantenimiento");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });

        menualumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FELIZ.GIF"))); // NOI18N
        menualumnos.setText("Alumnos");
        menualumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menualumnosMouseClicked(evt);
            }
        });
        jMenu5.add(menualumnos);

        menucursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar.jpg"))); // NOI18N
        menucursos.setText("Cursos");
        menucursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menucursosMouseClicked(evt);
            }
        });
        jMenu5.add(menucursos);

        menuprofesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b_usrcheck.png"))); // NOI18N
        menuprofesores.setText("Profesores");
        menuprofesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuprofesoresMouseClicked(evt);
            }
        });
        jMenu5.add(menuprofesores);

        menunotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        menunotas.setText("Notas");
        menunotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menunotasMouseClicked(evt);
            }
        });
        jMenu5.add(menunotas);

        jMenuBar1.add(jMenu5);

        jMenu10.setText("Ayuda");

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/material.gif"))); // NOI18N
        jMenu12.setText("Desarrolado por");
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenu10.add(jMenu12);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlumnos)
                    .addComponent(btnNotas))
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProfesores)
                    .addComponent(btnCursos))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(194, 194, 194))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlumnos)
                    .addComponent(btnProfesores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCursos)
                    .addComponent(btnNotas))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menualumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menualumnosMouseClicked
        // TODO add your handling code here:
        FRMAlumnos f=new FRMAlumnos();
        f.show();
    }//GEN-LAST:event_menualumnosMouseClicked

    private void menucursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menucursosMouseClicked
        // TODO add your handling code here:
        FRMCursos f=new FRMCursos();
        f.show();
    }//GEN-LAST:event_menucursosMouseClicked

    private void menuprofesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuprofesoresMouseClicked
        // TODO add your handling code here:
        FRMProfesores f=new FRMProfesores();
        f.show();
    }//GEN-LAST:event_menuprofesoresMouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        // TODO add your handling code here:
        AcercaDe f=new AcercaDe();
        f.show();
    }//GEN-LAST:event_jMenu12MouseClicked

    private void menunotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menunotasMouseClicked
        // TODO add your handling code here:
        FRMNotas f=new FRMNotas();
        f.show();
    }//GEN-LAST:event_menunotasMouseClicked

    private void btnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosActionPerformed
        // TODO add your handling code here:
        FRMCursos f=new FRMCursos();
        f.show();
    }//GEN-LAST:event_btnCursosActionPerformed

    private void btnProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesoresActionPerformed
        // TODO add your handling code here:
        FRMProfesores f=new FRMProfesores();
        f.show();
    }//GEN-LAST:event_btnProfesoresActionPerformed

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        // TODO add your handling code here:
        FRMAlumnos f=new FRMAlumnos();
        f.show();
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
        // TODO add your handling code here:
        FRMNotas f=new FRMNotas();
        f.show();
    }//GEN-LAST:event_btnNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnCursos;
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton btnProfesores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menualumnos;
    private javax.swing.JMenu menucursos;
    private javax.swing.JMenu menunotas;
    private javax.swing.JMenu menuprofesores;
    // End of variables declaration//GEN-END:variables
}
